export const EMAIL_EVENTS = {
  requestCreatedChurchConfirmation: {
    key: "request.created.church_confirmation",
    label: "Request posted confirmation",
    description: "Sent to a church after they create a service request.",
    subject: "Request posted: {{REQUEST_TITLE}}",
    category: "activity",
    suggestedTemplateName: "request-created-church-confirmation",
    templateEnv: "RESEND_TEMPLATE_REQUEST_CREATED_CHURCH_CONFIRMATION",
    tags: [
      { name: "CHURCH_NAME", description: "The church profile name." },
      { name: "REQUEST_TITLE", description: "The title of the new request." },
      { name: "SERVICE_DATE", description: "The request service date as YYYY-MM-DD." },
      { name: "REQUEST_URL", description: "Absolute link to the request detail page." },
    ],
  },
  requestInviteMusician: {
    key: "request.invite.musician",
    label: "Musician invitation",
    description: "Sent to a musician when a church invites them to an open request.",
    subject: "{{CHURCH_NAME}} invited you to {{REQUEST_TITLE}}",
    category: "activity",
    suggestedTemplateName: "request-invite-musician",
    templateEnv: "RESEND_TEMPLATE_REQUEST_INVITE_MUSICIAN",
    tags: [
      { name: "MUSICIAN_NAME", description: "The musician display name." },
      { name: "CHURCH_NAME", description: "The inviting church name." },
      { name: "REQUEST_TITLE", description: "The request title." },
      { name: "SERVICE_DATE", description: "The request service date as YYYY-MM-DD." },
      { name: "FEE_LABEL", description: "Formatted fee text, such as $250 Per service or Fee TBD." },
      { name: "THREAD_URL", description: "Absolute link to the invitation message thread." },
    ],
  },
  messageReceived: {
    key: "message.received",
    label: "Message received",
    description: "Sent when a user receives a new message in a booking/request thread.",
    subject: "New message from {{SENDER_NAME}}",
    category: "activity",
    suggestedTemplateName: "message-received",
    templateEnv: "RESEND_TEMPLATE_MESSAGE_RECEIVED",
    tags: [
      { name: "RECIPIENT_NAME", description: "The recipient display name." },
      { name: "SENDER_NAME", description: "The sender display name." },
      { name: "REQUEST_TITLE", description: "The request title." },
      { name: "MESSAGE_PREVIEW", description: "Short preview of the message body." },
      { name: "THREAD_URL", description: "Absolute link to the message thread." },
    ],
  },
  proposalReceived: {
    key: "proposal.received",
    label: "Proposal received",
    description: "Sent to a musician when a church sends or revises proposal terms.",
    subject: "{{CHURCH_NAME}} sent proposal terms",
    category: "activity",
    suggestedTemplateName: "proposal-received",
    templateEnv: "RESEND_TEMPLATE_PROPOSAL_RECEIVED",
    tags: [
      { name: "RECIPIENT_NAME", description: "The musician display name." },
      { name: "CHURCH_NAME", description: "The church name." },
      { name: "REQUEST_TITLE", description: "The request title." },
      { name: "SERVICE_DATE", description: "The request service date as YYYY-MM-DD." },
      { name: "FEE_LABEL", description: "Formatted fee text." },
      { name: "THREAD_URL", description: "Absolute link to the proposal thread." },
    ],
  },
  bookingConfirmed: {
    key: "booking.confirmed",
    label: "Booking confirmed",
    description: "Sent to both sides when a proposal is accepted and the booking is scheduled.",
    subject: "Booking confirmed: {{REQUEST_TITLE}}",
    category: "critical",
    suggestedTemplateName: "booking-confirmed",
    templateEnv: "RESEND_TEMPLATE_BOOKING_CONFIRMED",
    tags: [
      { name: "RECIPIENT_NAME", description: "The recipient display name." },
      { name: "COUNTERPARTY_NAME", description: "The other party's name." },
      { name: "REQUEST_TITLE", description: "The request title." },
      { name: "SERVICE_DATE", description: "The booking service date as YYYY-MM-DD." },
      { name: "FEE_LABEL", description: "Formatted fee text." },
      { name: "THREAD_URL", description: "Absolute link to the booking conversation." },
    ],
  },
  bookingCancelled: {
    key: "booking.cancelled",
    label: "Booking cancelled",
    description: "Sent to both sides when a confirmed booking is cancelled.",
    subject: "Booking cancelled: {{REQUEST_TITLE}}",
    category: "critical",
    suggestedTemplateName: "booking-cancelled",
    templateEnv: "RESEND_TEMPLATE_BOOKING_CANCELLED",
    tags: [
      { name: "RECIPIENT_NAME", description: "The recipient display name." },
      { name: "CANCELLED_BY_NAME", description: "The party who cancelled." },
      { name: "REQUEST_TITLE", description: "The request title." },
      { name: "SERVICE_DATE", description: "The booking service date as YYYY-MM-DD." },
      { name: "POLICY_LABEL", description: "Cancellation policy label." },
      { name: "REASON", description: "Cancellation reason/category." },
      { name: "THREAD_URL", description: "Absolute link to the booking conversation." },
    ],
  },
  paymentFailed: {
    key: "payment.failed",
    label: "Payment failed",
    description: "Sent when an event-day payment capture fails.",
    subject: "Payment failed for {{REQUEST_TITLE}}",
    category: "critical",
    suggestedTemplateName: "payment-failed",
    templateEnv: "RESEND_TEMPLATE_PAYMENT_FAILED",
    tags: [
      { name: "RECIPIENT_NAME", description: "The recipient display name." },
      { name: "REQUEST_TITLE", description: "The request title." },
      { name: "SERVICE_DATE", description: "The booking service date as YYYY-MM-DD." },
      { name: "AMOUNT", description: "Formatted charge amount." },
      { name: "ERROR_MESSAGE", description: "Failure detail from Stripe." },
      { name: "ACTION_URL", description: "Absolute link for follow-up." },
    ],
  },
  musicianOnboarding: {
    key: "musician.onboarding",
    label: "Musician onboarding",
    description: "Sent to a musician when they first create their account.",
    subject: "Welcome to Sunday Musician, {{MUSICIAN_NAME}}",
    category: "system",
    suggestedTemplateName: "musician-onboarding",
    templateEnv: "RESEND_TEMPLATE_MUSICIAN_ONBOARDING",
    tags: [
      { name: "MUSICIAN_NAME", description: "The musician display name." },
      { name: "PROFILE_URL", description: "Absolute link to the musician profile editor." },
      { name: "DASHBOARD_URL", description: "Absolute link to the musician dashboard." },
      { name: "PAYOUTS_URL", description: "Absolute link to connect Stripe for payouts." },
    ],
  },
  reviewPrompt: {
    key: "review.prompt",
    label: "Review prompt",
    description: "Sent after a completed service when a side has not reviewed yet.",
    subject: "How was {{COUNTERPARTY_NAME}}?",
    category: "activity",
    suggestedTemplateName: "review-prompt",
    templateEnv: "RESEND_TEMPLATE_REVIEW_PROMPT",
    tags: [
      { name: "RECIPIENT_NAME", description: "The recipient display name." },
      { name: "COUNTERPARTY_NAME", description: "The other party's name." },
      { name: "SERVICE_DATE", description: "The service date as YYYY-MM-DD." },
      { name: "REVIEW_URL", description: "Absolute link to the review page." },
    ],
  },
  reviewReminder: {
    key: "review.reminder",
    label: "Review reminder",
    description: "Sent near the end of the private review window.",
    subject: "Reminder: review {{COUNTERPARTY_NAME}}",
    category: "activity",
    suggestedTemplateName: "review-reminder",
    templateEnv: "RESEND_TEMPLATE_REVIEW_REMINDER",
    tags: [
      { name: "RECIPIENT_NAME", description: "The recipient display name." },
      { name: "COUNTERPARTY_NAME", description: "The other party's name." },
      { name: "SERVICE_DATE", description: "The service date as YYYY-MM-DD." },
      { name: "DAYS_REMAINING", description: "Days remaining in the review window." },
      { name: "REVIEW_URL", description: "Absolute link to the review page." },
    ],
  },
  reviewReleased: {
    key: "review.released",
    label: "Review released",
    description: "Sent when submitted reviews become visible.",
    subject: "Your review of {{COUNTERPARTY_NAME}} is now visible",
    category: "activity",
    suggestedTemplateName: "review-released",
    templateEnv: "RESEND_TEMPLATE_REVIEW_RELEASED",
    tags: [
      { name: "RECIPIENT_NAME", description: "The recipient display name." },
      { name: "COUNTERPARTY_NAME", description: "The other party's name." },
      { name: "SERVICE_DATE", description: "The service date as YYYY-MM-DD." },
      { name: "REVIEW_URL", description: "Absolute link to the review page." },
    ],
  },
} as const;

export function configuredTemplateId(event: { templateEnv: string }) {
  return process.env[event.templateEnv]?.trim() || undefined;
}
