import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/app/admin/_lib/require-admin";
import { logAdminAction } from "@/app/admin/_lib/audit";
import { withJsonErrors } from "@/lib/api/handler";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function addDays(date: string, days: number) {
  const d = new Date(`${date}T12:00:00Z`);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

// Creates a real reviewable booking between existing profiles. The records are
// deliberately titled "Review Lab" so they are easy to recognize and clean up.
export const POST = withJsonErrors(async (req: Request) => {
  const gate = await requireAdmin();
  if (!gate.ok) return gate.response;

  const body = await req.json().catch(() => ({}));
  const churchProfileId = typeof body.churchProfileId === "string" ? body.churchProfileId : null;
  const musicianProfileId = typeof body.musicianProfileId === "string" ? body.musicianProfileId : null;
  const serviceDate = typeof body.serviceDate === "string" && /^\d{4}-\d{2}-\d{2}$/.test(body.serviceDate)
    ? body.serviceDate
    : addDays(new Date().toISOString().slice(0, 10), -1);

  if (!churchProfileId || !musicianProfileId) {
    return NextResponse.json({ error: "churchProfileId and musicianProfileId required" }, { status: 400 });
  }

  const admin = createAdminClient();
  const [{ data: church }, { data: musician }] = await Promise.all([
    admin.from("church_profiles").select("id, church_name").eq("id", churchProfileId).maybeSingle(),
    admin.from("musician_profiles").select("id, profiles(display_name)").eq("id", musicianProfileId).maybeSingle(),
  ]);
  if (!church || !musician) return NextResponse.json({ error: "Church or musician profile not found" }, { status: 404 });

  const title = `Review Lab — ${new Date().toISOString().slice(0, 19)}`;
  const { data: request, error: requestErr } = await admin.from("service_requests").insert({
    church_profile_id: churchProfileId,
    title,
    service_type: "Review Lab",
    service_date: serviceDate,
    service_time: "10:00",
    location: "Review Lab",
    instruments_needed: ["Review tester"],
    rehearsals: "None",
    tech_setup: [],
    offered_fee: 100,
    fee_type: "Flat",
    setlist_url: null,
    notes: "Generated by the admin Review Lab.",
    status: "filled",
  }).select("id").single();
  if (requestErr || !request) return NextResponse.json({ error: requestErr?.message ?? "Could not create request" }, { status: 500 });

  const { data: thread, error: threadErr } = await admin.from("threads").insert({
    request_id: request.id,
    church_profile_id: churchProfileId,
    musician_profile_id: musicianProfileId,
    archived_at: new Date().toISOString(),
    archive_reason: "request_closed",
  }).select("id").single();
  if (threadErr || !thread) return NextResponse.json({ error: threadErr?.message ?? "Could not create thread" }, { status: 500 });

  const { data: booking, error: bookingErr } = await admin.from("bookings").insert({
    request_id: request.id,
    thread_id: thread.id,
    church_profile_id: churchProfileId,
    musician_profile_id: musicianProfileId,
    service_date: serviceDate,
    fee: 100,
    fee_type: "Flat",
  }).select("id").single();
  if (bookingErr || !booking) return NextResponse.json({ error: bookingErr?.message ?? "Could not create booking" }, { status: 500 });

  const revealAt = `${addDays(serviceDate, 7)}T00:00:00.000Z`;
  const { data: period, error: periodErr } = await admin.from("review_periods").insert({
    booking_id: booking.id,
    reveal_at: revealAt,
  }).select("id").single();
  if (periodErr || !period) return NextResponse.json({ error: periodErr?.message ?? "Could not create review period" }, { status: 500 });

  await logAdminAction({
    actorId: gate.actor.id,
    actorEmail: gate.actor.email,
    action: "create_review_lab_scenario",
    targetType: "request",
    targetId: request.id,
    targetLabel: title,
    metadata: { periodId: period.id, bookingId: booking.id, churchProfileId, musicianProfileId, serviceDate },
  });

  return NextResponse.json({ ok: true, requestId: request.id, threadId: thread.id, bookingId: booking.id, periodId: period.id });
});
